name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: |
        if [ -f ./gradlew ]; then
          chmod +x ./gradlew
        fi

    - name: Build with Gradle
      run: |
        if [ -f ./gradlew ]; then
          ./gradlew assembleDebug
        else
          gradle assembleDebug
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk




